name 'news_crawler'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures news_crawler'
long_description 'Installs/Configures news_crawler'
version '0.1.0'
